### ISSUE TITLE
大哥 你有两个文件未加入仓库，编译不了

### ISSUE THREAD

**Issue by zpzhangwenhan** [ImbaQ/MyLinkToken#4]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS2001	Source file 'D:\MyLinkToken-master\MyLinkToken-master\MyLinkToken\LinkClass\KeyStoreEx.cs' could not be found.	MyLinkToken	D:\MyLinkToken-master\MyLinkToken-master\MyLinkToken\CSC	1	活动

**Comment by HuiMi24** [comment]
对啊，缺少文件没法编译。能否麻烦上传一下。非常感谢！！！

**Comment by 190389518** [comment]
刚网上看了一下，这个dll托管到NuGet了的。可用使用NuGet命令安装。
Install-Package iHomeSoft.Helper -Version 1.0.0.5

安装后调用改成这样就可以了：iHomeSoft.Helper.iniHelper(Application.StartupPath + "\\rename.ini");
