### ISSUE TITLE
缺少引用文件

### ISSUE THREAD

**Issue by tanglifeng** [ImbaQ/MyLinkToken#5]
iHomeSoft.Helper，找不到

**Comment by 190389518** [comment]
刚网上看了一下，这个dll托管到NuGet了的。可用使用NuGet命令安装。
Install-Package iHomeSoft.Helper -Version 1.0.0.5

安装后调用改成这样就可以了：iHomeSoft.Helper.iniHelper(Application.StartupPath + "\\rename.ini");
